/* =========================================================
   SuppleNavi - 飲み合わせ判定ルール
   ---------------------------------------------------------
   判定は2段構え:
     1) PAIRS    … 個別ペアの明示ルール（優先）
     2) TAG_RULES… 作用機序タグの組み合わせで拾う汎用ルール
                   （PAIRS に無い組み合わせもここで検出できる）

   lv: 'ng'      = × 避ける
       'caution' = △ 注意（時間をずらす／量を控える）
       'good'    = ◎ 相性がよい（相乗・吸収向上）
       'ok'      = ○ 問題の報告なし（既定値。明示不要）

   短文主義: msg は一行で言い切る。詳細は how（対処）に分ける。
   ========================================================= */

/* ---------- 1) 個別ペアルール ---------- */
const PAIRS = [

/* === × 避ける ===================================================== */
{a:'st_johns', b:'d_op', lv:'ng', msg:'避妊効果が落ちる', how:'併用しない。ピル服用中はセントジョーンズワートを使わない'},
{a:'st_johns', b:'d_ssri', lv:'ng', msg:'セロトニン症候群のリスク', how:'併用しない。発汗・震え・混乱が出たら受診'},
{a:'st_johns', b:'d_warfarin', lv:'ng', msg:'ワルファリンの効果が弱まる', how:'併用しない'},
{a:'st_johns', b:'d_immunosuppress', lv:'ng', msg:'薬の血中濃度が下がり治療が失敗しうる', how:'併用しない。主治医に必ず申告'},
{a:'st_johns', b:'d_statin', lv:'ng', msg:'スタチンの効果が弱まる', how:'併用しない'},
{a:'st_johns', b:'tryptophan', lv:'ng', msg:'セロトニン過剰のリスク', how:'同時に使わない'},
{a:'st_johns', b:'d_bp', lv:'caution', msg:'降圧薬の効果が弱まる可能性', how:'血圧を測りながら医師に相談'},

{a:'f_natto', b:'d_warfarin', lv:'ng', msg:'ワルファリンが効かなくなる', how:'服用中は納豆を食べない（ビタミンKが極めて多い）'},
{a:'vit_k', b:'d_warfarin', lv:'ng', msg:'ワルファリンの効果を直接打ち消す', how:'ビタミンKサプリは使わない'},
{a:'f_greenleaf', b:'d_warfarin', lv:'caution', msg:'ビタミンKで効きが変わる', how:'禁止ではなく「毎日同じ量」を守る。青汁の新規開始は必ず相談'},

{a:'omega3', b:'d_warfarin', lv:'ng', msg:'出血しやすくなる', how:'自己判断で併用しない。手術・抜歯の1〜2週前は中止'},
{a:'ginkgo', b:'d_warfarin', lv:'ng', msg:'出血しやすくなる', how:'併用しない'},
{a:'nattokinase', b:'d_warfarin', lv:'ng', msg:'血栓を溶かす作用が重なる', how:'併用しない'},
{a:'nattokinase', b:'d_doac', lv:'ng', msg:'出血リスクが大きく上がる', how:'併用しない'},
{a:'ginkgo', b:'d_doac', lv:'ng', msg:'出血しやすくなる', how:'併用しない。手術前は中止'},
{a:'omega3', b:'d_doac', lv:'caution', msg:'出血しやすくなる方向', how:'医師に申告。1日3,000mg超は避ける'},
{a:'cranberry', b:'d_warfarin', lv:'ng', msg:'ワルファリンが効きすぎる', how:'サプリ・ジュースの大量摂取を避ける'},
{a:'f_cranberry_juice', b:'d_warfarin', lv:'ng', msg:'ワルファリンが効きすぎる', how:'常飲しない'},
{a:'glucosamine', b:'d_warfarin', lv:'ng', msg:'INRが上がる報告あり', how:'併用しない、または頻回にINRを測定'},
{a:'chondroitin', b:'d_warfarin', lv:'caution', msg:'抗凝固作用が強まる可能性', how:'医師に申告し、INRを確認'},
{a:'coq10', b:'d_warfarin', lv:'caution', msg:'ワルファリンの効果が弱まる報告', how:'開始・中止時はINRを測定'},
{a:'ginseng', b:'d_warfarin', lv:'caution', msg:'ワルファリンの効果が弱まる報告', how:'併用は医師管理下で'},

{a:'f_grapefruit', b:'d_statin', lv:'ng', msg:'血中濃度が上がり筋障害のリスク', how:'時間をずらしても回避できない。柑橘を替える（オレンジ・みかんはOK）'},
{a:'f_grapefruit', b:'d_bp', lv:'ng', msg:'効きすぎて血圧が下がりすぎる', how:'カルシウム拮抗薬服用中は摂らない'},
{a:'f_grapefruit', b:'d_immunosuppress', lv:'ng', msg:'血中濃度が危険域まで上がる', how:'完全に避ける'},
{a:'f_seville', b:'d_statin', lv:'ng', msg:'グレープフルーツと同じ酵素阻害', how:'ダイダイ・ポメロ・ライムも避ける'},
{a:'f_seville', b:'d_bp', lv:'ng', msg:'グレープフルーツと同じ酵素阻害', how:'マーマレードにも注意'},

{a:'tryptophan', b:'d_ssri', lv:'ng', msg:'セロトニン症候群のリスク', how:'併用しない'},
{a:'mucuna', b:'d_ssri', lv:'ng', msg:'MAO阻害薬との併用で血圧急上昇の危険', how:'併用しない'},
{a:'mucuna', b:'f_tyramine', lv:'caution', msg:'血圧が上がる方向に重なる', how:'MAO阻害薬を併用中なら熟成食品も避ける'},
{a:'yohimbe', b:'d_ssri', lv:'ng', msg:'血圧急上昇・不安発作のリスク', how:'ヨヒンベは使用しない'},
{a:'yohimbe', b:'d_bp', lv:'ng', msg:'血圧が不安定になる', how:'ヨヒンベは使用しない'},
{a:'yohimbe', b:'caffeine', lv:'ng', msg:'興奮作用が重なり不整脈のリスク', how:'ヨヒンベは使用しない'},

{a:'echinacea', b:'d_immunosuppress', lv:'ng', msg:'免疫抑制の効果を打ち消す方向', how:'併用しない'},
{a:'ashwagandha', b:'d_immunosuppress', lv:'ng', msg:'免疫を刺激する方向で干渉', how:'併用しない'},
{a:'green_tea_ex', b:'f_alcohol', lv:'ng', msg:'肝臓への負担が重なる', how:'濃縮カテキンサプリと飲酒は同日に重ねない'},
{a:'garcinia', b:'f_alcohol', lv:'ng', msg:'肝障害の報告があり負担が重なる', how:'併用しない'},
{a:'garcinia', b:'d_ssri', lv:'ng', msg:'セロトニンに作用し重複するおそれ', how:'併用しない'},
{a:'licorice', b:'d_bp', lv:'ng', msg:'血圧が上がり降圧薬と相反する', how:'甘草の長期摂取を避ける。漢方の重複を薬剤師に確認'},
{a:'licorice', b:'potassium', lv:'caution', msg:'カリウムが下がる方向と補う方向が競合', how:'甘草を続けるなら血液検査でカリウムを確認'},
{a:'f_licorice_food', b:'d_bp', lv:'caution', msg:'漢方・のど飴の甘草が血圧を上げうる', how:'服用中の漢方を薬剤師に一覧で見せる'},
{a:'melatonin', b:'d_sedative', lv:'ng', msg:'眠気・ふらつきが強く出る', how:'併用しない。日本では食品として販売できない成分'},
{a:'valerian', b:'d_sedative', lv:'ng', msg:'眠気・ふらつきが強く出る', how:'併用しない。運転は避ける'},
{a:'valerian', b:'f_alcohol', lv:'ng', msg:'鎮静作用が重なる', how:'同時に摂らない'},
{a:'f_alcohol', b:'d_sedative', lv:'ng', msg:'呼吸抑制・記憶の抜けのリスク', how:'服用日は飲酒しない'},
{a:'garlic', b:'d_doac', lv:'caution', msg:'出血しやすくなる方向', how:'サプリの高用量は避ける。手術前は中止'},
{a:'ginkgo', b:'omega3', lv:'caution', msg:'血が固まりにくい作用が重なる', how:'両方とるなら量を控え、手術前は中止'},
{a:'ginkgo', b:'nattokinase', lv:'ng', msg:'抗血栓作用が強く重なる', how:'どちらか一方にする'},
{a:'nattokinase', b:'omega3', lv:'caution', msg:'血が固まりにくい作用が重なる', how:'あざができやすい・鼻血が出るなら中止して相談'},

/* === △ 注意（多くは「時間をずらす」で解決） ======================== */
{a:'calcium', b:'iron', lv:'caution', msg:'お互いの吸収を下げ合う', how:'2時間以上ずらす（例: 鉄は朝、カルシウムは夜）'},
{a:'calcium', b:'zinc', lv:'caution', msg:'亜鉛の吸収が落ちる', how:'2時間以上ずらす'},
{a:'calcium', b:'magnesium', lv:'caution', msg:'高用量同士では吸収を奪い合う', how:'1回500mg以下に分ける。同時配合のサプリなら気にしなくてよい'},
{a:'calcium', b:'d_abx', lv:'ng', msg:'抗菌薬が吸収されず効かない', how:'抗菌薬の2時間前〜4時間後を空ける'},
{a:'iron', b:'d_abx', lv:'ng', msg:'抗菌薬が吸収されず効かない', how:'2時間以上ずらす'},
{a:'magnesium', b:'d_abx', lv:'ng', msg:'抗菌薬が吸収されず効かない', how:'2時間以上ずらす'},
{a:'zinc', b:'d_abx', lv:'caution', msg:'抗菌薬の吸収が落ちる', how:'2時間以上ずらす'},
{a:'iron', b:'d_thyroid', lv:'ng', msg:'甲状腺薬が吸収されない', how:'甲状腺薬は起床時に空腹で。鉄は4時間後以降'},
{a:'calcium', b:'d_thyroid', lv:'ng', msg:'甲状腺薬が吸収されない', how:'4時間以上ずらす'},
{a:'f_soy', b:'d_thyroid', lv:'caution', msg:'甲状腺薬の吸収が落ちる', how:'4時間ほどずらす'},
{a:'prebiotics', b:'d_thyroid', lv:'caution', msg:'食物繊維が吸収を遅らせる', how:'薬とは時間をずらす'},
{a:'iron', b:'zinc', lv:'caution', msg:'吸収経路が競合する', how:'別の時間帯に分ける'},
{a:'zinc', b:'copper', lv:'caution', msg:'亜鉛の高用量が銅を不足させる', how:'亜鉛40mg/日以下に。長期なら銅1mgを併せる'},
{a:'iron', b:'f_tea', lv:'caution', msg:'タンニンで鉄の吸収が落ちる', how:'鉄の前後30分〜1時間はお茶を控える'},
{a:'iron', b:'f_coffee', lv:'caution', msg:'タンニンで鉄の吸収が落ちる', how:'1時間ずらす'},
{a:'iron', b:'f_milk', lv:'caution', msg:'カルシウムで鉄の吸収が落ちる', how:'2時間ずらす'},
{a:'iron', b:'curcumin', lv:'caution', msg:'クルクミンが鉄の吸収を妨げる', how:'時間をずらす。鉄欠乏がある人は特に'},
{a:'iron', b:'green_tea_ex', lv:'caution', msg:'カテキンが鉄の吸収を妨げる', how:'時間をずらす'},
{a:'iron', b:'f_wholegrain', lv:'caution', msg:'フィチン酸で吸収が落ちる', how:'食事から1〜2時間ずらす'},
{a:'zinc', b:'f_wholegrain', lv:'caution', msg:'フィチン酸で吸収が落ちる', how:'食事から1〜2時間ずらす'},
{a:'zinc', b:'f_milk', lv:'caution', msg:'カルシウムで吸収が落ちる', how:'2時間ずらす'},
{a:'calcium', b:'f_highsalt', lv:'caution', msg:'塩分がカルシウムの排出を増やす', how:'骨対策なら減塩もセットで'},
{a:'calcium', b:'caffeine', lv:'caution', msg:'カフェインがカルシウムの排出を増やす', how:'カフェインは1日400mg以内に'},
{a:'biotin', b:'f_rawegg', lv:'caution', msg:'生の卵白がビオチンを吸収させない', how:'卵は加熱する（加熱すれば問題なし）'},
{a:'biotin', b:'alpha_lipoic', lv:'caution', msg:'吸収経路を奪い合う', how:'別の時間帯に分ける'},
{a:'probiotics', b:'d_abx', lv:'caution', msg:'抗菌薬で菌が死んでしまう', how:'2〜3時間ずらす。抗菌薬中〜後の整腸目的なら有用'},
{a:'chitosan', b:'vit_a', lv:'caution', msg:'脂溶性ビタミンの吸収を妨げる', how:'時間をずらす（キトサンは食事直前、ビタミンは別の食事で）'},
{a:'chitosan', b:'vit_d', lv:'caution', msg:'脂溶性ビタミンの吸収を妨げる', how:'時間をずらす'},
{a:'chitosan', b:'vit_e', lv:'caution', msg:'脂溶性ビタミンの吸収を妨げる', how:'時間をずらす'},
{a:'chitosan', b:'omega3', lv:'caution', msg:'油の吸収を妨げるためオメガ3も減る', how:'時間をずらす'},
{a:'chitosan', b:'d_warfarin', lv:'caution', msg:'ワルファリンの効果が変わりうる', how:'医師に申告'},
{a:'prebiotics', b:'iron', lv:'caution', msg:'食物繊維が吸収を遅らせる', how:'時間をずらす'},
{a:'lutein', b:'beta_carotene', lv:'caution', msg:'吸収経路が競合する', how:'高用量の同時摂取を避ける。通常量なら問題は小さい'},

{a:'vit_d', b:'calcium', lv:'good', msg:'カルシウムの吸収を高める王道の組み合わせ', how:'ただし合計量に注意（Ca 2,500mg/日・D 100μg/日が上限）'},
{a:'vit_d', b:'magnesium', lv:'good', msg:'マグネシウムはビタミンDの活性化に必要', how:'併せてとると効率がよい'},

{a:'vit_a', b:'vit_d', lv:'caution', msg:'どちらも溜まるタイプで過剰になりやすい', how:'マルチビタミンと単体サプリの重複を確認'},
{a:'vit_a', b:'beta_carotene', lv:'caution', msg:'合算で上限を超えやすい', how:'ビタミンA総量2,700μgRAE/日を超えない'},
{a:'beta_carotene', b:'f_alcohol', lv:'caution', msg:'肝臓への負担が増える報告', how:'高用量サプリと日常的な飲酒は重ねない'},
{a:'vit_e', b:'d_doac', lv:'caution', msg:'出血しやすくなる方向', how:'400 IU/日以上は避ける。手術前は中止'},
{a:'vit_e', b:'vit_k', lv:'caution', msg:'高用量EがビタミンKの働きを妨げうる', how:'Eは常用量にとどめる'},
{a:'niacin', b:'f_alcohol', lv:'caution', msg:'顔の赤み・肝負担が強く出る', how:'ナイアシン摂取日は飲酒を控える'},
{a:'vit_c', b:'iron', lv:'good', msg:'鉄の吸収を大きく高める', how:'鉄と同時に。ビタミンC 100mg程度でも効果あり'},
{a:'vit_c', b:'f_wholegrain', lv:'good', msg:'フィチン酸の吸収阻害を打ち消す方向', how:'植物性の鉄をとるときに一緒に'},
{a:'vit_c', b:'vit_e', lv:'good', msg:'抗酸化の働きをお互いに回復させる', how:'同時摂取でよい'},
{a:'vit_b12', b:'folate', lv:'good', msg:'血をつくる工程で協働し、B12欠乏を隠すのを防ぐ', how:'葉酸サプリはB12入りを選ぶと安心'},

{a:'caffeine', b:'f_coffee', lv:'caution', msg:'カフェインが合算で過剰になる', how:'1日400mg以内（コーヒー1杯≒60〜100mg）'},
{a:'caffeine', b:'f_energy', lv:'ng', msg:'合算で急性中毒域に届きうる', how:'併用しない'},
{a:'caffeine', b:'f_tea', lv:'caution', msg:'カフェインが合算される', how:'合計量を計算する'},
{a:'caffeine', b:'melatonin', lv:'ng', msg:'覚醒と睡眠で作用が真逆', how:'同時にとる意味がない。カフェインは就寝6時間前まで'},
{a:'caffeine', b:'valerian', lv:'ng', msg:'作用が真逆で打ち消し合う', how:'時間帯を完全に分ける'},
{a:'caffeine', b:'glycine', lv:'caution', msg:'寝つきを助ける作用が打ち消される', how:'カフェインは午後早めまで'},
{a:'caffeine', b:'theanine', lv:'good', msg:'カフェインの尖りを和らげ集中が保ちやすい', how:'カフェイン100mg + テアニン200mg が定番'},
{a:'caffeine', b:'creatine', lv:'caution', msg:'高用量カフェインがクレアチンの効果を打ち消す報告', how:'プレワークアウトのカフェインは控えめに'},
{a:'caffeine', b:'iron', lv:'caution', msg:'鉄の吸収が落ちる', how:'1時間ずらす'},
{a:'caffeine', b:'d_bp', lv:'caution', msg:'血圧が上がる方向で相反する', how:'家庭で血圧を測って確認'},
{a:'f_energy', b:'d_bp', lv:'caution', msg:'血圧・心拍が上がる', how:'常飲しない'},
{a:'f_alcohol', b:'vit_b1', lv:'good', msg:'飲酒でB1が消耗するため補うのは合理的', how:'ただし飲酒量そのものを減らすのが本筋'},

{a:'alpha_lipoic', b:'d_diabetes', lv:'ng', msg:'低血糖のリスク', how:'自己判断で併用しない。血糖自己測定を'},
{a:'chromium', b:'d_diabetes', lv:'caution', msg:'血糖が下がりすぎる可能性', how:'医師に申告し血糖を測る'},
{a:'ginseng', b:'d_diabetes', lv:'caution', msg:'血糖が下がる方向に重なる', how:'血糖を測りながら'},
{a:'prebiotics', b:'d_diabetes', lv:'caution', msg:'血糖の下がり方が変わる', how:'開始時は血糖を確認'},
{a:'glucosamine', b:'d_diabetes', lv:'caution', msg:'血糖への影響が議論されている', how:'血糖を測りながら'},

{a:'arginine', b:'d_bp', lv:'caution', msg:'血圧が下がりすぎる可能性', how:'医師に申告。ふらつきが出たら中止'},
{a:'citrulline', b:'d_bp', lv:'caution', msg:'血圧が下がりすぎる可能性', how:'医師に申告'},
{a:'arginine', b:'citrulline', lv:'caution', msg:'血管拡張作用が重なる', how:'両方とるなら合計量を控える'},
{a:'gaba', b:'d_bp', lv:'caution', msg:'血圧を下げる方向が重なる', how:'家庭血圧を測って確認'},
{a:'coq10', b:'d_bp', lv:'caution', msg:'血圧を下げる方向が重なる', how:'血圧を測って確認'},
{a:'omega3', b:'d_bp', lv:'caution', msg:'血圧を下げる方向が重なる', how:'通常は問題ないが測定を'},
{a:'potassium', b:'d_bp', lv:'ng', msg:'高カリウム血症のリスク', how:'ACE阻害薬・ARB・カリウム保持性利尿薬との併用は医師管理下でのみ'},

{a:'ashwagandha', b:'d_thyroid', lv:'ng', msg:'甲状腺ホルモンが上がりすぎるおそれ', how:'併用しない、または医師管理下で採血'},
{a:'iodine', b:'d_thyroid', lv:'ng', msg:'甲状腺機能が乱れる', how:'併用しない。昆布サプリも避ける'},
{a:'maca', b:'d_thyroid', lv:'caution', msg:'ゴイトロゲンが甲状腺に影響しうる', how:'加熱品を選び量を控える'},
{a:'selenium', b:'d_thyroid', lv:'caution', msg:'甲状腺の代謝に関わる', how:'上限（男450/女350μg）を超えない'},
{a:'isoflavone', b:'d_thyroid', lv:'caution', msg:'甲状腺薬の吸収を下げる', how:'4時間ずらす'},
{a:'carnitine', b:'d_thyroid', lv:'caution', msg:'甲状腺ホルモンの働きを弱める報告', how:'甲状腺疾患があれば医師に相談'},

{a:'ashwagandha', b:'d_sedative', lv:'caution', msg:'眠気が強まる', how:'量を控え、運転を避ける'},
{a:'ashwagandha', b:'f_alcohol', lv:'caution', msg:'眠気・肝負担が重なる', how:'同日に重ねない'},
{a:'theanine', b:'d_sedative', lv:'caution', msg:'眠気が強まる可能性', how:'まずは低用量から'},
{a:'gaba', b:'d_sedative', lv:'caution', msg:'眠気が強まる可能性', how:'医師に申告'},
{a:'glycine', b:'d_sedative', lv:'caution', msg:'作用が重なる', how:'併用の可否を医師に確認'},
{a:'melatonin', b:'f_alcohol', lv:'ng', msg:'アルコールがメラトニンの働きを乱す', how:'同時に摂らない'},

{a:'zinc', b:'saw_palmetto', lv:'caution', msg:'ホルモン系への作用が重なる', how:'前立腺の薬を使っている人は医師に相談'},
{a:'saw_palmetto', b:'d_doac', lv:'caution', msg:'弱い抗血小板作用が重なる', how:'手術前は中止'},
{a:'isoflavone', b:'chasteberry', lv:'caution', msg:'ホルモン系への作用が重なる', how:'どちらか一方から始める'},
{a:'chasteberry', b:'d_op', lv:'caution', msg:'ピルの働きと干渉する可能性', how:'医師に相談'},
{a:'isoflavone', b:'d_op', lv:'caution', msg:'ホルモン作用が重なる', how:'ホルモン療法中は主治医に確認'},
{a:'black_cohosh', b:'f_alcohol', lv:'ng', msg:'肝臓への負担が重なる', how:'同日に重ねない。だるさ・黄色い尿が出たら受診'},
{a:'black_cohosh', b:'d_op', lv:'caution', msg:'ホルモン作用が干渉しうる', how:'医師に相談'},
{a:'isoflavone', b:'f_soy', lv:'caution', msg:'食事分と合算して上限を超えやすい', how:'合計70〜75mg/日（アグリコン換算）以内に'},

{a:'curcumin', b:'d_doac', lv:'caution', msg:'血が固まりにくくなる方向', how:'高用量は避け、手術前は中止'},
{a:'green_tea_ex', b:'caffeine', lv:'caution', msg:'カフェインが合算される', how:'カフェインフリー表記を確認'},
{a:'milk_thistle', b:'f_alcohol', lv:'caution', msg:'肝ケア目的なら飲酒を減らすのが本筋', how:'サプリで飲酒を正当化しない'},
{a:'protein_whey', b:'f_milk', lv:'caution', msg:'乳糖が重なりお腹がゆるくなることがある', how:'WPI・加水分解型に替える'},
{a:'krill', b:'omega3', lv:'caution', msg:'オメガ3が合算される', how:'合計3,000mg/日を超えない'},
{a:'krill', b:'d_doac', lv:'ng', msg:'出血しやすくなる', how:'併用しない'},
{a:'glucosamine', b:'chitosan', lv:'caution', msg:'どちらも甲殻類由来が多い', how:'甲殻類アレルギーの人は原料表示を確認'},
{a:'mct', b:'prebiotics', lv:'caution', msg:'お腹がゆるくなる作用が重なる', how:'どちらも少量から'},
{a:'magnesium', b:'prebiotics', lv:'caution', msg:'お腹がゆるくなる作用が重なる', how:'マグネシウムを減らして調整'},
{a:'nmn', b:'d_immunosuppress', lv:'caution', msg:'NAD経路への影響が議論されている', how:'治療中は主治医に確認'},
{a:'resveratrol', b:'d_doac', lv:'caution', msg:'血が固まりにくくなる方向', how:'手術前は中止'},
{a:'bilberry', b:'d_doac', lv:'caution', msg:'弱い抗血小板作用が重なる', how:'高用量は避ける'},
{a:'f_grapefruit', b:'d_sedative', lv:'ng', msg:'睡眠薬が効きすぎる', how:'服用中は避ける'},
{a:'f_grapefruit', b:'d_op', lv:'caution', msg:'ホルモンの血中濃度が上がりうる', how:'常飲を避ける'},
{a:'f_grapefruit', b:'st_johns', lv:'caution', msg:'酵素への作用が真逆で予測しにくい', how:'どちらもやめるのが無難'},

/* === ◎ 相性がよい ================================================= */
{a:'vit_d', b:'vit_k', lv:'good', msg:'カルシウムを骨へ運ぶ流れが揃う', how:'D+K2のセットが骨対策の定番。ワルファリン服用中は不可'},
{a:'magnesium', b:'glycine', lv:'good', msg:'どちらも寝つきを助ける方向', how:'就寝30分前に'},
{a:'magnesium', b:'theanine', lv:'good', msg:'リラックス方向で噛み合う', how:'就寝前に'},
{a:'theanine', b:'gaba', lv:'good', msg:'リラックス系として併用実績が多い', how:'夜のリラックス目的で'},
{a:'glycine', b:'theanine', lv:'good', msg:'寝つき+リラックスで補完的', how:'就寝30分前に'},
{a:'creatine', b:'protein_whey', lv:'good', msg:'筋トレの土台として最も実績のある組み合わせ', how:'運動後に一緒でよい'},
{a:'creatine', b:'bcaa', lv:'ok', msg:'併用は可能だがBCAAの追加効果は小さい', how:'プロテインが足りていればBCAAは不要'},
{a:'citrulline', b:'creatine', lv:'good', msg:'運動パフォーマンス目的で相性がよい', how:'運動前にシトルリン、毎日クレアチン'},
{a:'curcumin', b:'omega3', lv:'good', msg:'炎症を抑える方向で補完的', how:'ただし抗凝固薬服用中は両方とも要注意'},
{a:'lutein', b:'astaxanthin', lv:'good', msg:'目のケアとして役割が違い補完的', how:'食後に一緒でよい'},
{a:'lutein', b:'omega3', lv:'good', msg:'脂溶性ルテインの吸収が上がる', how:'食後に一緒に'},
{a:'probiotics', b:'prebiotics', lv:'good', msg:'菌とそのエサをセットで入れられる', how:'シンバイオティクス。イヌリンは少量から'},
{a:'iron', b:'folate', lv:'good', msg:'血をつくる材料が揃う', how:'貧血対策の基本セット'},
{a:'iron', b:'vit_b12', lv:'good', msg:'血をつくる材料が揃う', how:'併用でよい'},
{a:'collagen', b:'vit_c', lv:'good', msg:'コラーゲンの合成にビタミンCが必要', how:'同時に。C 100mg以上を目安に'},
{a:'zinc', b:'vit_c', lv:'good', msg:'免疫・肌の面で補完的', how:'亜鉛は食後に'},
{a:'coq10', b:'d_statin', lv:'good', msg:'スタチンで減るCoQ10を補う考え方', how:'筋痛対策として。ただし効果は個人差が大きい'},
{a:'vit_e', b:'selenium', lv:'good', msg:'抗酸化の働きで協働する', how:'セレンは上限を守る'},
{a:'protein_whey', b:'vit_d', lv:'good', msg:'筋肉づくりで補完的', how:'併用でよい'},
{a:'hyaluronic', b:'collagen', lv:'good', msg:'肌の水分と弾力で役割が違う', how:'併用でよい'},
{a:'ceramide', b:'collagen', lv:'good', msg:'バリア機能と弾力で補完的', how:'食後に'},
{a:'f_water', b:'creatine', lv:'good', msg:'クレアチンは水分が必要', how:'1日1.5〜2Lの水分を'},
{a:'astaxanthin', b:'omega3', lv:'good', msg:'脂溶性の吸収が上がる', how:'食後に一緒に'},
{a:'vit_d', b:'omega3', lv:'good', msg:'どちらも脂溶性で食後にまとめられる', how:'食後に一緒に'},
];

/* ---------- 2) タグベース汎用ルール ----------
   PAIRS に登録がない組み合わせでも、作用機序が衝突すれば検出する。
   tagA × tagB の両方が別々のアイテムに存在すれば発火。         */
const TAG_RULES = [
 {tagA:'antiplatelet', tagB:'anticoagulant', lv:'ng',
  msg:'血が固まりにくくなる作用が重なる', how:'自己判断で併用しない。手術・抜歯の1〜2週前は中止'},
 {tagA:'fibrinolytic', tagB:'anticoagulant', lv:'ng',
  msg:'血栓を溶かす作用が重なる', how:'併用しない'},
 {tagA:'antiplatelet', tagB:'antiplatelet', lv:'caution',
  msg:'血が固まりにくくなる作用が重なる', how:'両方とるなら量を控え、手術前は中止'},
 /* 抗血小板 × ワルファリン拮抗は、抗凝固薬を服用していなければ実害の報告がない。
    薬（rx）が選択されている場合のみ意味を持つため汎用ルールからは外す */

 {tagA:'cyp3a4_inducer', tagB:'cyp3a4_substrate', lv:'ng',
  msg:'薬を分解する酵素が強まり薬が効かなくなる', how:'併用しない。処方薬がある人は自己判断で使わない'},
 {tagA:'cyp3a4_inhibitor', tagB:'cyp3a4_substrate', lv:'ng',
  msg:'薬の分解が止まり効きすぎる', how:'時間をずらしても回避できない。摂取自体を避ける'},
 {tagA:'cyp3a4_inhibitor', tagB:'narrow_ti', lv:'ng',
  msg:'効き目の幅が狭い薬の血中濃度が危険域に上がる', how:'完全に避ける'},

 {tagA:'serotonin', tagB:'serotonin_rx', lv:'ng',
  msg:'セロトニンが過剰になるリスク', how:'併用しない'},
 {tagA:'serotonin', tagB:'serotonin', lv:'caution',
  msg:'セロトニンに働く成分が重なる', how:'どちらか一方にする'},
 {tagA:'dopamine', tagB:'maoi', lv:'ng',
  msg:'血圧が急上昇するおそれ', how:'併用しない'},
 {tagA:'maoi_conflict', tagB:'serotonin_rx', lv:'ng',
  msg:'抗うつ薬との併用で重大な副作用のリスク', how:'併用しない'},
 {tagA:'tyramine', tagB:'maoi', lv:'ng',
  msg:'血圧が急上昇する（チーズ効果）', how:'MAO阻害薬使用中は熟成食品を避ける'},

 {tagA:'chelate', tagB:'chelate_victim', lv:'ng',
  msg:'金属イオンと結合して薬が吸収されない', how:'2時間以上（甲状腺薬は4時間）ずらす'},
 {tagA:'divalent_cation', tagB:'chelate_victim', lv:'ng',
  msg:'ミネラルが薬と結合して吸収を妨げる', how:'2時間以上ずらす'},
 {tagA:'divalent_cation', tagB:'divalent_cation', lv:'caution',
  msg:'同じ吸収経路を奪い合う', how:'時間帯を分ける。同時配合サプリなら問題は小さい'},
 {tagA:'ca_rich', tagB:'chelate_victim', lv:'ng',
  msg:'カルシウムが薬と結合して吸収を妨げる', how:'2時間以上ずらす'},
 {tagA:'phytate', tagB:'divalent_cation', lv:'caution',
  msg:'フィチン酸がミネラルの吸収を下げる', how:'食事から1〜2時間ずらす'},
 /* 鉄がらみは fe_source（鉄そのもの）に限定して発火させる。
    blood タグはB12・葉酸にも付くため、そちらでは誤検出になっていた */
 {tagA:'tannin', tagB:'fe_source', lv:'caution',
  msg:'タンニンが鉄の吸収を妨げる', how:'30分〜1時間ずらす'},
 {tagA:'fe_absorb_down', tagB:'fe_source', lv:'caution',
  msg:'鉄の吸収が下がる', how:'時間をずらす'},
 /* absorb_block は「吸収を遅らせる」程度の食物繊維も含むため、
    脂溶性ビタミンの吸収を実際に妨げる fat_block のみを衝突扱いにする */
 {tagA:'fat_block', tagB:'fat_soluble', lv:'caution',
  msg:'油の吸収を妨げるため脂溶性成分も減る', how:'時間をずらす'},
 {tagA:'biotin_block', tagB:'skin_hair', lv:'caution',
  msg:'ビオチンの吸収が妨げられる', how:'卵は加熱する'},
 {tagA:'biotin_compete', tagB:'skin_hair', lv:'caution',
  msg:'吸収経路を奪い合う', how:'時間帯を分ける'},

 {tagA:'vit_k_rich', tagB:'anticoagulant', lv:'ng',
  msg:'ビタミンKが抗凝固薬の効果を打ち消す', how:'量を急に変えない。新規開始は必ず医師に相談'},
 {tagA:'clotting', tagB:'anticoagulant', lv:'ng',
  msg:'血を固める方向と固まりにくくする薬が相反する', how:'医師の管理下でのみ'},
 {tagA:'warfarin_antagonist', tagB:'anticoagulant', lv:'ng',
  msg:'抗凝固薬の効果が弱まる', how:'併用しない、またはINRを頻回に測定'},
 {tagA:'warfarin_interact', tagB:'anticoagulant', lv:'ng',
  msg:'抗凝固薬の効き方が変わる', how:'医師に申告し検査値を確認'},

 {tagA:'sedative', tagB:'sedative_rx', lv:'ng',
  msg:'眠気・ふらつきが強く出る', how:'併用しない。運転を避ける'},
 {tagA:'sedative', tagB:'sedative', lv:'caution',
  msg:'鎮静作用が重なる', how:'量を控え、運転前は避ける'},
 {tagA:'sedative_mild', tagB:'sedative_rx', lv:'caution',
  msg:'眠気が強まる可能性', how:'医師に申告し低用量から'},
 {tagA:'stimulant', tagB:'sedative', lv:'ng',
  msg:'覚醒と鎮静で作用が真逆', how:'時間帯を完全に分ける'},
 {tagA:'stimulant', tagB:'sleep', lv:'ng',
  msg:'睡眠を助ける作用が打ち消される', how:'刺激系は午後早めまでに'},
 {tagA:'stimulant', tagB:'arrhythmia', lv:'caution',
  msg:'心拍・血圧が上がる作用が重なる', how:'合計量を抑える'},
 {tagA:'caffeine', tagB:'caffeine', lv:'caution',
  msg:'カフェインが合算される', how:'1日400mg以内で計算する'},
 {tagA:'caffeine', tagB:'sleep', lv:'ng',
  msg:'寝つきを妨げる', how:'就寝6時間前以降は摂らない'},

 {tagA:'bp_up', tagB:'bp_rx', lv:'ng',
  msg:'血圧を上げる方向で薬と相反する', how:'家庭血圧を測り医師に相談'},
 {tagA:'bp_lower', tagB:'bp_rx', lv:'caution',
  msg:'血圧が下がりすぎる可能性', how:'血圧を測り、ふらつきが出たら中止'},
 /* bp_lower × bp_lower は降圧薬なしでは実害の報告がないため ○ 扱い（ルール化しない） */
 {tagA:'vasodilate', tagB:'bp_rx', lv:'caution',
  msg:'血管拡張が重なり血圧が下がりすぎる可能性', how:'医師に申告'},
 {tagA:'k_lower', tagB:'electrolyte', lv:'caution',
  msg:'カリウムのバランスが崩れる', how:'血液検査で確認'},
 {tagA:'electrolyte', tagB:'bp_rx', lv:'ng',
  msg:'高カリウム血症のリスク', how:'ACE阻害薬・ARB・カリウム保持性利尿薬との併用は医師管理下で'},

 {tagA:'glucose_lower', tagB:'glucose_rx', lv:'ng',
  msg:'低血糖のリスク', how:'自己判断で併用しない。血糖自己測定を'},
 {tagA:'glucose_lower', tagB:'glucose_lower', lv:'caution',
  msg:'血糖を下げる作用が重なる', how:'糖尿病薬を使っていなければ通常は問題ない'},

 {tagA:'thyroid', tagB:'thyroid_rx', lv:'ng',
  msg:'甲状腺の働きに影響しうる', how:'併用しない、または医師管理下で採血'},
 {tagA:'isoflavone_rich', tagB:'thyroid_rx', lv:'caution',
  msg:'甲状腺薬の吸収が落ちる', how:'4時間ずらす'},
 {tagA:'fiber', tagB:'chelate_victim', lv:'caution',
  msg:'食物繊維が薬の吸収を遅らせる', how:'薬とは時間をずらす'},

 {tagA:'immune_stim', tagB:'immunosuppress', lv:'ng',
  msg:'免疫抑制の治療を打ち消す方向', how:'併用しない'},
 /* liver は「肝ケア目的」と「肝負担リスク」の両方に付いていたため、
    負担リスク側だけを liver_risk に分離して衝突判定する */
 {tagA:'liver_risk', tagB:'liver_risk', lv:'caution',
  msg:'肝臓への負担が重なる可能性', how:'同時に複数を高用量で続けない。健診で肝機能を確認'},
 {tagA:'liver_risk', tagB:'alcohol', lv:'ng',
  msg:'肝臓への負担が重なる', how:'摂取する日は飲酒を控える'},
 {tagA:'high_risk', tagB:'rx', lv:'ng',
  msg:'注意度の高い成分と処方薬の組み合わせ', how:'必ず薬剤師・医師に確認してから'},
 {tagA:'accum_risk', tagB:'accum_risk', lv:'caution',
  msg:'体に溜まるタイプが重なり過剰になりやすい', how:'マルチビタミンとの重複を確認し上限量を守る'},
 {tagA:'gi_irritant', tagB:'gi_irritant', lv:'caution',
  msg:'胃腸への負担が重なる', how:'食後にし、少量から慣らす'},
 {tagA:'laxative', tagB:'fiber', lv:'caution',
  msg:'お腹がゆるくなる作用が重なる', how:'どちらも少量から'},
 {tagA:'hormone', tagB:'hormone_rx', lv:'caution',
  msg:'ホルモンへの作用が重なる', how:'ホルモン療法中は主治医に確認'},
 {tagA:'hormone', tagB:'hormone', lv:'caution',
  msg:'ホルモン系への作用が重なる', how:'どちらか一方から始める'},
 {tagA:'photosens', tagB:'skin_hair', lv:'caution',
  msg:'日光に敏感になる可能性', how:'日焼け対策を'},
 {tagA:'preg_avoid', tagB:'preg_benefit', lv:'caution',
  msg:'妊娠中・妊娠計画中は避ける成分が含まれる', how:'妊娠の可能性があるなら医師に確認'},
 {tagA:'psa_mask', tagB:'rx', lv:'caution',
  msg:'検査値に影響しうる', how:'健診・受診時に摂取中であることを伝える'},
 {tagA:'jp_not_food', tagB:'rx', lv:'ng',
  msg:'国内で食品として認められていない成分と処方薬の併用', how:'医師に相談する'},
];

/* ---------- 3) 単体での注意（他と組まなくても表示したいもの） ---------- */
const SOLO_ALERTS = [
 {id:'yohimbe', lv:'ng', msg:'日本では食品への使用が認められていない成分', how:'使用しない。海外サプリの成分表示を確認する'},
 {id:'melatonin', lv:'caution', msg:'日本では食品として販売できない成分', how:'不眠は医療機関で相談するのが確実'},
 {id:'st_johns', lv:'caution', msg:'処方薬との相互作用が非常に多い', how:'薬を1剤でも飲んでいるなら使う前に薬剤師へ'},
 {id:'garcinia', lv:'caution', msg:'肝障害の症例報告があり効果は小さい', how:'他の手段を優先する'},
 {id:'green_tea_ex', lv:'caution', msg:'濃縮サプリの空腹時・高用量で肝リスク', how:'EGCG 800mg/日未満、食後に'},
 {id:'licorice', lv:'caution', msg:'漢方・のど飴との重複で過剰になりやすい', how:'服用中の漢方を薬剤師に一覧で確認'},
 {id:'caffeine', lv:'caution', msg:'錠剤は一気に過剰量になりやすい', how:'1回200mg・1日400mgまで。飲料分と合算する'},
 {id:'iodine', lv:'caution', msg:'日本の食事では既に十分足りている', how:'サプリでの追加は基本的に不要'},
 {id:'selenium', lv:'caution', msg:'必要量と上限量の幅が狭い', how:'マルチビタミンとの重複を確認'},
 {id:'vit_a', lv:'caution', msg:'妊娠初期の過剰摂取は避ける成分', how:'妊娠中・計画中はβカロテン型を選ぶ'},
];
