/* =========================================================
   SuppleNavi - 成分・食品マスター
   ---------------------------------------------------------
   kind : 'supp'(サプリ成分) | 'food'(食品・飲料) | 'drug'(薬の系統/参考)
   tags : 相互作用ルール判定に使う作用機序タグ（js/data-rules.js が参照）
   dose : 成人の目安量。基準の出典は basis に明記。
   ul   : 耐容上限量 / 注意ライン
   ========================================================= */

const ITEMS = [

/* ================= 脂溶性ビタミン ================= */
{id:'vit_a', kind:'supp', name:'ビタミンA（レチノール）', cat:'ビタミン',
 alias:['レチノール','ビタミンA','retinol','βカロテン由来でないA'],
 tags:['fat_soluble','accum_risk','liver','preg_caution'],
 doseM:'850 μgRAE/日', doseF:'650 μgRAE/日', ul:'2,700 μgRAE/日',
 basis:'日本人の食事摂取基準2020（18〜64歳）',
 timing:'食後（脂質と一緒で吸収↑）',
 note:'体に溜まるタイプ。妊娠初期の過剰摂取は胎児への影響が知られる。βカロテンは体内で必要量だけAに変わるため上限の考え方が別。'},

{id:'beta_carotene', kind:'supp', name:'βカロテン', cat:'ビタミン',
 alias:['ベータカロテン','beta-carotene','プロビタミンA'],
 tags:['fat_soluble','antioxidant'],
 doseM:'2〜6 mg/日', doseF:'2〜6 mg/日', ul:'明確な上限なし（サプリは15mg/日程度まで）',
 basis:'一般的なサプリ表示量',
 timing:'食後',
 note:'喫煙者の高用量長期摂取で肺がんリスク上昇の報告（CARET/ATBC試験）。喫煙者はサプリでの高用量を避ける。'},

{id:'vit_d', kind:'supp', name:'ビタミンD', cat:'ビタミン',
 alias:['ビタミンD3','コレカルシフェロール','D3','cholecalciferol','VD'],
 tags:['fat_soluble','accum_risk','ca_absorb'],
 doseM:'8.5 μg（340 IU)/日 が目安量。サプリは25 μg(1,000 IU)前後が主流', doseF:'同左', ul:'100 μg（4,000 IU）/日',
 basis:'日本人の食事摂取基準2020（目安量）',
 timing:'食後（脂質と一緒で吸収↑）',
 note:'カルシウムの吸収を高める。カルシウム剤・活性型ビタミンD処方薬との重複で高カルシウム血症に注意。'},

{id:'vit_e', kind:'supp', name:'ビタミンE', cat:'ビタミン',
 alias:['トコフェロール','α-トコフェロール','tocopherol','VE'],
 tags:['fat_soluble','antioxidant','antiplatelet'],
 doseM:'6.0 mg/日（目安量）', doseF:'5.0 mg/日（目安量）', ul:'約650〜900 mg/日（性・年齢で異なる）',
 basis:'日本人の食事摂取基準2020',
 timing:'食後',
 note:'高用量（400 IU/日以上）で血が固まりにくくなる方向に働く。手術前や抗凝固薬の使用中は要相談。'},

{id:'vit_k', kind:'supp', name:'ビタミンK', cat:'ビタミン',
 alias:['ビタミンK2','メナキノン','MK-7','フィロキノン','VK'],
 tags:['fat_soluble','clotting','warfarin_antagonist'],
 doseM:'150 μg/日（目安量）', doseF:'150 μg/日（目安量）', ul:'設定なし',
 basis:'日本人の食事摂取基準2020',
 timing:'食後',
 note:'血を固める働きを助ける。ワルファリン（抗凝固薬）の効果を弱めるため、服用中は摂取量を一定に保つ必要がある。'},

/* ================= 水溶性ビタミン ================= */
{id:'vit_b1', kind:'supp', name:'ビタミンB1', cat:'ビタミン',
 alias:['チアミン','thiamine','B1'],
 tags:['water_soluble','energy'],
 doseM:'1.4 mg/日', doseF:'1.1 mg/日', ul:'設定なし',
 basis:'日本人の食事摂取基準2020（推奨量）',
 timing:'食後', note:'糖質をエネルギーに変える工程で使われる。アルコールをよく飲む人は消耗しやすい。'},

{id:'vit_b2', kind:'supp', name:'ビタミンB2', cat:'ビタミン',
 alias:['リボフラビン','riboflavin','B2'],
 tags:['water_soluble','energy'],
 doseM:'1.6 mg/日', doseF:'1.2 mg/日', ul:'設定なし',
 basis:'日本人の食事摂取基準2020（推奨量）',
 timing:'食後', note:'尿が黄色くなるのは吸収されなかった分が出ているだけで、体への害ではない。'},

{id:'niacin', kind:'supp', name:'ナイアシン（B3）', cat:'ビタミン',
 alias:['ニコチン酸','ニコチンアミド','nicotinamide','B3','NAM'],
 tags:['water_soluble','energy','vasodilate','liver_risk'],
 doseM:'15 mgNE/日', doseF:'11 mgNE/日', ul:'ニコチンアミドで男300 / 女250 mg/日',
 basis:'日本人の食事摂取基準2020',
 timing:'食後', note:'ニコチン酸型を高用量とると顔が赤くなり熱くなる（ナイアシンフラッシュ）。高用量長期で肝機能への負担の報告あり。'},

{id:'vit_b6', kind:'supp', name:'ビタミンB6', cat:'ビタミン',
 alias:['ピリドキシン','P5P','pyridoxine','B6'],
 tags:['water_soluble','neuro'],
 doseM:'1.4 mg/日', doseF:'1.1 mg/日', ul:'男55〜60 / 女45 mg/日',
 basis:'日本人の食事摂取基準2020',
 timing:'食後', note:'長期・高用量（目安100mg/日超を数ヶ月）で手足のしびれなど末梢神経の症状が報告されている。'},

{id:'vit_b12', kind:'supp', name:'ビタミンB12', cat:'ビタミン',
 alias:['コバラミン','メチルコバラミン','シアノコバラミン','B12'],
 tags:['water_soluble','blood'],
 doseM:'2.4 μg/日', doseF:'2.4 μg/日', ul:'設定なし',
 basis:'日本人の食事摂取基準2020（推奨量）',
 timing:'いつでも', note:'動物性食品にしか実質含まれないため、完全菜食では不足しやすい。胃酸を抑える薬の長期使用でも吸収が落ちる。'},

{id:'folate', kind:'supp', name:'葉酸', cat:'ビタミン',
 alias:['フォラシン','folic acid','ビタミンM','プテロイルグルタミン酸','ようさん'],
 tags:['water_soluble','blood','preg_benefit'],
 doseM:'240 μg/日', doseF:'240 μg/日（妊娠計画中〜初期は+400 μg/日）', ul:'サプリ由来で900〜1,000 μg/日',
 basis:'日本人の食事摂取基準2020',
 timing:'いつでも', note:'妊娠を計画する女性は追加摂取が推奨される数少ない成分。単独の高用量はB12欠乏を隠すことがある。'},

{id:'biotin', kind:'supp', name:'ビオチン', cat:'ビタミン',
 alias:['ビタミンH','biotin','B7'],
 tags:['water_soluble','skin_hair'],
 doseM:'50 μg/日（目安量）', doseF:'50 μg/日（目安量）', ul:'設定なし',
 basis:'日本人の食事摂取基準2020',
 timing:'いつでも', note:'高用量摂取中は甲状腺やホルモンの血液検査が誤った値になることがある。検査前は申告を。'},

{id:'pantothenic', kind:'supp', name:'パントテン酸（B5）', cat:'ビタミン',
 alias:['ビタミンB5','pantothenic acid','ぱんとてんさん'],
 tags:['water_soluble','energy'],
 doseM:'5〜6 mg/日（目安量）', doseF:'5 mg/日（目安量）', ul:'設定なし',
 basis:'日本人の食事摂取基準2020', timing:'食後', note:'幅広い食品に含まれ、通常の食事で不足しにくい。'},

{id:'vit_c', kind:'supp', name:'ビタミンC', cat:'ビタミン',
 alias:['アスコルビン酸','ascorbic acid','VC'],
 tags:['water_soluble','antioxidant','fe_absorb_up','urine_acid'],
 doseM:'100 mg/日', doseF:'100 mg/日', ul:'設定なし（1,000 mg/日超で下痢等）',
 basis:'日本人の食事摂取基準2020（推奨量）',
 timing:'こまめに分けて', note:'鉄の吸収を助ける。一度に大量にとると余剰は尿に出るうえ、下痢や胃の不快感が出やすい。'},

/* ================= ミネラル ================= */
{id:'calcium', kind:'supp', name:'カルシウム', cat:'ミネラル',
 alias:['Ca','炭酸カルシウム','クエン酸カルシウム','乳酸カルシウム'],
 tags:['divalent_cation','bone','chelate'],
 doseM:'750〜800 mg/日', doseF:'650 mg/日', ul:'2,500 mg/日',
 basis:'日本人の食事摂取基準2020',
 timing:'食後。1回500mg以下に分ける', note:'鉄・亜鉛・マグネシウムや一部の抗菌薬と同時に飲むとお互いの吸収を落とす。時間をずらすのが基本。'},

{id:'magnesium', kind:'supp', name:'マグネシウム', cat:'ミネラル',
 alias:['Mg','酸化マグネシウム','クエン酸マグネシウム','グリシン酸マグネシウム'],
 tags:['divalent_cation','chelate','laxative','sedative_mild','muscle'],
 doseM:'370 mg/日', doseF:'290 mg/日', ul:'サプリ由来で350 mg/日（食品由来は上限なし）',
 basis:'日本人の食事摂取基準2020',
 timing:'夕食後〜就寝前', note:'とりすぎるとお腹がゆるくなる。腎機能が低下している人は体内に溜まりやすいため要相談。'},

{id:'iron', kind:'supp', name:'鉄', cat:'ミネラル',
 alias:['Fe','ヘム鉄','非ヘム鉄','フマル酸第一鉄','クエン酸鉄','てつ','へむてつ'],
 tags:['divalent_cation','chelate','blood','fe_source','gi_irritant','oxidative'],
 doseM:'7.5 mg/日', doseF:'10.5 mg/日（月経あり）／6.5 mg/日（月経なし）', ul:'男50 / 女40 mg/日',
 basis:'日本人の食事摂取基準2020',
 timing:'空腹時が吸収は良いが胃に負担。胃が弱い人は食後', note:'お茶・コーヒーのタンニン、カルシウム、亜鉛で吸収が下がる。ビタミンCで吸収が上がる。'},

{id:'zinc', kind:'supp', name:'亜鉛', cat:'ミネラル',
 alias:['Zn','グルコン酸亜鉛','ピコリン酸亜鉛','あえん'],
 tags:['divalent_cation','chelate','immune','hormone','skin_hair'],
 doseM:'11 mg/日', doseF:'8 mg/日', ul:'男40〜45 / 女35 mg/日',
 basis:'日本人の食事摂取基準2020',
 timing:'食後（空腹時は吐き気が出やすい）', note:'長期の高用量は銅の欠乏を招く。銅と併せてとる、または40mg/日を超えないのが基本。'},

{id:'copper', kind:'supp', name:'銅', cat:'ミネラル',
 alias:['Cu','グルコン酸銅','どう'],
 tags:['divalent_cation','chelate','blood'],
 doseM:'0.9 mg/日', doseF:'0.7 mg/日', ul:'7 mg/日',
 basis:'日本人の食事摂取基準2020', timing:'食後', note:'亜鉛の高用量摂取で不足しやすくなる。亜鉛:銅 = 10:1〜15:1 程度が目安とされる。'},

{id:'selenium', kind:'supp', name:'セレン', cat:'ミネラル',
 alias:['Se','セレニウム','selenium','セレノメチオニン'],
 tags:['antioxidant','accum_risk','thyroid'],
 doseM:'30 μg/日', doseF:'25 μg/日', ul:'男450 / 女350 μg/日',
 basis:'日本人の食事摂取基準2020', timing:'食後',
 note:'上限と必要量の幅が狭い成分。マルチビタミンとブラジルナッツの併用など、重複に注意。'},

{id:'iodine', kind:'supp', name:'ヨウ素', cat:'ミネラル',
 alias:['ヨード','I','昆布由来ヨウ素','kelp','ようそ','よーど'],
 tags:['thyroid','accum_risk'],
 doseM:'130 μg/日', doseF:'130 μg/日', ul:'3,000 μg/日',
 basis:'日本人の食事摂取基準2020', timing:'食後',
 note:'日本は昆布・海藻から十分にとれており、サプリでの追加は過剰になりやすい。甲状腺疾患がある人は特に注意。'},

{id:'chromium', kind:'supp', name:'クロム', cat:'ミネラル',
 alias:['Cr','ピコリン酸クロム','クロミウム'],
 tags:['glucose_lower'],
 doseM:'10 μg/日（目安量）', doseF:'10 μg/日（目安量）', ul:'500 μg/日',
 basis:'日本人の食事摂取基準2020', timing:'食後',
 note:'血糖に関わるため、糖尿病治療薬との併用では低血糖側に振れる可能性がある。'},

{id:'manganese', kind:'supp', name:'マンガン', cat:'ミネラル',
 alias:['Mn'], tags:['divalent_cation','chelate'],
 doseM:'4.0 mg/日（目安量）', doseF:'3.5 mg/日（目安量）', ul:'11 mg/日',
 basis:'日本人の食事摂取基準2020', timing:'食後', note:'通常の食事で足りやすい。鉄と吸収経路が競合する。'},

{id:'potassium', kind:'supp', name:'カリウム', cat:'ミネラル',
 alias:['K','塩化カリウム'], tags:['electrolyte','bp_lower','kidney_caution'],
 doseM:'2,500 mg/日（目安量）', doseF:'2,000 mg/日（目安量）', ul:'設定なし（サプリでの追加は慎重に）',
 basis:'日本人の食事摂取基準2020', timing:'食後',
 note:'腎機能低下、カリウム保持性利尿薬、ACE阻害薬・ARB使用中は高カリウム血症のリスクがあり、サプリでの追加は医師の管理下で。'},

/* ================= 脂質・脂肪酸 ================= */
{id:'omega3', kind:'supp', name:'EPA・DHA（オメガ3／魚油）', cat:'脂質',
 alias:['EPA','DHA','フィッシュオイル','魚油','オメガ3','omega-3','n-3系','ぎょゆ','おめがすりー','さかなのあぶら'],
 tags:['antiplatelet','lipid_lower','anti_inflam','fat_soluble','bp_lower'],
 doseM:'EPA+DHA 1,000〜2,000 mg/日', doseF:'同左', ul:'3,000 mg/日超は出血傾向に注意（FDA目安）',
 basis:'各種RCT・機能性表示食品の実配合量',
 timing:'食後（脂質と一緒で吸収↑）',
 note:'血が固まりにくくなる方向に働く。抗凝固薬・抗血小板薬との併用、手術・抜歯の前は要相談。'},

{id:'krill', kind:'supp', name:'クリルオイル', cat:'脂質',
 alias:['オキアミオイル','krill oil'], tags:['antiplatelet','lipid_lower','fat_soluble','allergen_shellfish'],
 doseM:'1,000〜2,000 mg/日', doseF:'同左', ul:'—',
 basis:'一般的なサプリ表示量', timing:'食後',
 note:'甲殻類アレルギーの人は避ける。オメガ3としての注意点は魚油と同じ。'},

{id:'mct', kind:'supp', name:'MCTオイル（中鎖脂肪酸）', cat:'脂質',
 alias:['中鎖脂肪酸','MCT','ココナッツオイル由来','ちゅうさしぼうさん'], tags:['energy','gi_irritant'],
 doseM:'5〜15 g/日', doseF:'同左', ul:'—',
 basis:'一般的な摂取目安', timing:'食事と一緒に少量から',
 note:'いきなり大さじ1以上とると下痢・腹痛が出やすい。小さじ1から慣らす。'},

/* ================= アミノ酸・タンパク ================= */
{id:'protein_whey', kind:'supp', name:'ホエイプロテイン', cat:'アミノ酸・タンパク',
 alias:['プロテイン','whey','乳清タンパク'], tags:['muscle','allergen_milk','kidney_caution'],
 doseM:'体重1kgあたり1.2〜2.0 g/日を食事+サプリ合計で', doseF:'同左', ul:'—',
 basis:'ISSN（国際スポーツ栄養学会）ポジションスタンド',
 timing:'運動後／間食', note:'乳アレルギー・乳糖不耐の人は加水分解型やWPIを。腎機能低下時は総タンパク量を医師と相談。'},

{id:'bcaa', kind:'supp', name:'BCAA', cat:'アミノ酸・タンパク',
 alias:['分岐鎖アミノ酸','ロイシン','バリン','イソロイシン','leucine'],
 tags:['muscle','energy'],
 doseM:'5〜10 g/日', doseF:'同左', ul:'—',
 basis:'一般的なサプリ表示量', timing:'運動前・運動中',
 note:'十分なタンパク質をとれている人での追加効果は限定的という報告が多い。'},

{id:'eaa', kind:'supp', name:'EAA（必須アミノ酸）', cat:'アミノ酸・タンパク',
 alias:['必須アミノ酸','essential amino acid','ひっすあみのさん'], tags:['muscle'],
 doseM:'6〜15 g/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量',
 timing:'運動前後', note:'BCAAを含む上位互換的な位置づけ。空腹時に大量にとると胃が重くなることがある。'},

{id:'creatine', kind:'supp', name:'クレアチン', cat:'アミノ酸・タンパク',
 alias:['クレアチンモノハイドレート','creatine','クレアピュア'],
 tags:['muscle','water_retention','kidney_caution','caffeine_conflict'],
 doseM:'3〜5 g/日（毎日）', doseF:'同左', ul:'—',
 basis:'ISSNポジションスタンド（エビデンス最も強いサプリの一つ）',
 timing:'いつでも毎日。運動後がやや有利', note:'体内に水を引き込むため体重が1〜2kg増えることがある（脂肪ではない）。水分を多めに。'},

{id:'hmb', kind:'supp', name:'HMB', cat:'アミノ酸・タンパク',
 alias:['β-ヒドロキシ-β-メチル酪酸','hmb'], tags:['muscle'],
 doseM:'3 g/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量',
 timing:'食後', note:'トレーニング初心者・高齢者では効果報告があるが、鍛えている人での追加効果は小さいという報告が多い。'},

{id:'arginine', kind:'supp', name:'L-アルギニン', cat:'アミノ酸・タンパク',
 alias:['アルギニン','arginine'], tags:['vasodilate','bp_lower','herpes_risk'],
 doseM:'3〜6 g/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量',
 timing:'空腹時', note:'血管を広げる方向に働くため、降圧薬・ED治療薬との併用で血圧が下がりすぎる可能性。'},

{id:'citrulline', kind:'supp', name:'L-シトルリン', cat:'アミノ酸・タンパク',
 alias:['シトルリン','citrulline','シトルリンマレート'], tags:['vasodilate','bp_lower','muscle'],
 doseM:'3〜8 g/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量',
 timing:'運動前', note:'アルギニンより血中濃度を上げやすい。降圧薬との併用は要注意。'},

{id:'theanine', kind:'supp', name:'L-テアニン', cat:'アミノ酸・タンパク',
 alias:['テアニン','theanine','緑茶アミノ酸'], tags:['sedative_mild','relax','bp_lower'],
 doseM:'100〜200 mg/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（睡眠の質・一時的ストレス）',
 timing:'就寝30分〜1時間前／日中のストレス時', note:'眠くなりすぎない穏やかなリラックス系。カフェインの尖りを和らげる組み合わせで使われる。'},

{id:'glycine', kind:'supp', name:'グリシン', cat:'アミノ酸・タンパク',
 alias:['glycine'], tags:['sleep','sedative_mild'],
 doseM:'3 g/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（睡眠の質）',
 timing:'就寝30分前', note:'深部体温を下げて寝つきを助ける方向。甘みがあり水に溶けやすい。'},

{id:'gaba', kind:'supp', name:'GABA', cat:'アミノ酸・タンパク',
 alias:['γ-アミノ酪酸','ギャバ','gaba'], tags:['sedative_mild','relax','bp_lower'],
 doseM:'28〜100 mg/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（ストレス・睡眠・血圧）',
 timing:'就寝前／ストレス時', note:'経口摂取分が脳にどれだけ届くかは議論がある。血圧を下げる届出もあり、降圧薬併用時は測定を。'},

{id:'tryptophan', kind:'supp', name:'L-トリプトファン', cat:'アミノ酸・タンパク',
 alias:['トリプトファン','tryptophan'], tags:['serotonin','sleep','sedative_mild'],
 doseM:'500〜1,000 mg/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量',
 timing:'就寝前（糖質と一緒だと脳へ入りやすい）',
 note:'セロトニンの材料。抗うつ薬（SSRI/SNRI/MAO阻害薬）との併用はセロトニン症候群のリスクがあり避ける。'},

{id:'taurine', kind:'supp', name:'タウリン', kindNote:'', cat:'アミノ酸・タンパク',
 alias:['taurine'], tags:['liver','energy','bp_lower'],
 doseM:'500〜2,000 mg/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量／医薬品では1,000〜3,000mg',
 timing:'食後', note:'エナジードリンクに多く配合されるが、そこでの覚醒感の主役はカフェイン。'},

{id:'carnitine', kind:'supp', name:'L-カルニチン', cat:'アミノ酸・タンパク',
 alias:['カルニチン','carnitine','アセチルLカルニチン'], tags:['fat_burn','thyroid'],
 doseM:'500〜1,000 mg/日', doseF:'同左', ul:'—', basis:'一般的なサプリ表示量',
 timing:'食後・運動前', note:'脂肪をエネルギーに運ぶ役。単独での減量効果は小さく、運動と組み合わせが前提。'},

{id:'collagen', kind:'supp', name:'コラーゲンペプチド', cat:'美容・その他',
 alias:['コラーゲン','collagen','低分子コラーゲン','フィッシュコラーゲン'],
 tags:['skin_hair','joint','allergen_fish'],
 doseM:'2.5〜10 g/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（肌の弾力・うるおい）',
 timing:'いつでも毎日', note:'即効性はなく8〜12週の継続が前提。魚由来は魚アレルギーに注意。'},

/* ================= ハーブ・植物 ================= */
{id:'st_johns', kind:'supp', name:'セントジョーンズワート', cat:'ハーブ',
 alias:['セイヨウオトギリソウ','St. Johns Wort','SJW','ハイペリカム'],
 tags:['cyp3a4_inducer','serotonin','photosens','high_risk'],
 doseM:'300 mg×3回/日（0.3%ヒペリシン抽出物）', doseF:'同左', ul:'—',
 basis:'欧州の伝統的使用・臨床試験',
 timing:'食後', note:'★最重要注意★ 薬を代謝する酵素を強く誘導し、経口避妊薬・抗HIV薬・免疫抑制薬・ワルファリン・一部の抗がん剤などの効果を弱める。厚生労働省も併用注意を通知。処方薬を1剤でも飲んでいる人は自己判断で使わない。'},

{id:'ginkgo', kind:'supp', name:'イチョウ葉エキス', cat:'ハーブ',
 alias:['イチョウ葉','ginkgo','ギンコウ','ginkgo biloba','いちょうは','いちょうよう'],
 tags:['antiplatelet','cognition','seizure_risk'],
 doseM:'120〜240 mg/日（EGb761規格）', doseF:'同左', ul:'—',
 basis:'欧州の医薬品的使用・臨床試験',
 timing:'食後・分割', note:'血が固まりにくくなる方向に働く。抗凝固薬・抗血小板薬との併用や手術前は避ける。てんかんのある人は発作閾値を下げる報告あり。'},

{id:'ginseng', kind:'supp', name:'高麗人参（オタネニンジン）', cat:'ハーブ',
 alias:['朝鮮人参','人参','ginseng','パナックス','紅参','こうらいにんじん','ちょうせんにんじん','にんじん'],
 tags:['stimulant_mild','glucose_lower','warfarin_interact','bp_up'],
 doseM:'200〜400 mg/日（標準化抽出物）', doseF:'同左', ul:'—',
 basis:'伝統的使用・臨床試験', timing:'朝〜日中（夜は寝つきに影響）',
 note:'ワルファリンの効果を弱める報告、血糖を下げる方向の報告がある。糖尿病薬・抗凝固薬併用時は要相談。'},

{id:'maca', kind:'supp', name:'マカ', cat:'ハーブ',
 alias:['maca','マカ根','ペルー人参'], tags:['hormone','stimulant_mild','thyroid'],
 doseM:'1,500〜3,000 mg/日', doseF:'同左', ul:'—',
 basis:'伝統的使用・小規模RCT', timing:'朝〜日中',
 note:'アブラナ科でゴイトロゲン（甲状腺のヨウ素利用を妨げる成分）を含むため、甲状腺疾患のある人は加熱品を選び量を控える。'},

{id:'mucuna', kind:'supp', name:'ムクナ（ハッショウマメ）', cat:'ハーブ',
 alias:['ムクナプルリエンス','mucuna','L-ドーパ','levodopa含有','ベルベットビーン'],
 tags:['dopamine','maoi_conflict','high_risk','bp_change'],
 doseM:'L-ドーパ換算で100〜300 mg/日相当', doseF:'同左', ul:'—',
 basis:'伝統的使用・パーキンソン病領域の小規模試験',
 timing:'空腹時', note:'★注意★ 天然のL-ドーパを含む。パーキンソン病治療薬（レボドパ製剤）、MAO阻害薬、抗精神病薬を使っている人は自己判断で併用しない。'},

{id:'ashwagandha', kind:'supp', name:'アシュワガンダ', cat:'ハーブ',
 alias:['ashwagandha','withania','インド人参','KSM-66'],
 tags:['sedative_mild','thyroid','immune_stim','liver_risk','preg_avoid'],
 doseM:'300〜600 mg/日（根の抽出物）', doseF:'同左', ul:'—',
 basis:'アーユルヴェーダの伝統的使用・複数RCT',
 timing:'夕食後〜就寝前', note:'甲状腺ホルモンを上げる方向の報告があり、甲状腺薬との併用は要注意。妊娠中は避ける。まれに肝機能への影響の報告あり。'},

{id:'valerian', kind:'supp', name:'バレリアン（セイヨウカノコソウ）', cat:'ハーブ',
 alias:['バレリアンルート','valerian','カノコソウ'], tags:['sedative','sleep'],
 doseM:'300〜600 mg/日（就寝前）', doseF:'同左', ul:'—',
 basis:'欧州の伝統的使用', timing:'就寝30分〜2時間前',
 note:'睡眠薬・抗不安薬・アルコールと重なると眠気やふらつきが強く出る。運転前は避ける。'},

{id:'echinacea', kind:'supp', name:'エキナセア', cat:'ハーブ',
 alias:['echinacea','ムラサキバレンギク'], tags:['immune_stim','liver_risk'],
 doseM:'300〜500 mg×3回/日（急性期の短期）', doseF:'同左', ul:'長期連用は避ける（目安8週まで）',
 basis:'伝統的使用・かぜ領域のRCT', timing:'食後',
 note:'免疫を刺激する方向に働くため、自己免疫疾患のある人や免疫抑制薬を使っている人は避ける。'},

{id:'curcumin', kind:'supp', name:'クルクミン（ウコン）', cat:'ハーブ',
 alias:['ウコン','ターメリック','curcumin','turmeric','秋ウコン'],
 tags:['antiplatelet','anti_inflam','fe_absorb_down','liver','bile'],
 doseM:'500〜1,500 mg/日（吸収改善型は少量で可）', doseF:'同左', ul:'—',
 basis:'複数RCT・伝統的使用', timing:'食後（脂質・ピペリンと吸収↑）',
 note:'鉄の吸収を妨げる報告があり、鉄剤と時間をずらす。胆石・胆道閉塞のある人は避ける。まれに肝機能への影響の報告あり。'},

{id:'milk_thistle', kind:'supp', name:'ミルクシスル（シリマリン）', cat:'ハーブ',
 alias:['マリアアザミ','シリマリン','silymarin','milk thistle'],
 tags:['liver','cyp_mild'], doseM:'200〜400 mg/日（シリマリン換算）', doseF:'同左', ul:'—',
 basis:'欧州の伝統的使用・肝領域の試験', timing:'食後',
 note:'肝臓のケア目的で使われる。キク科アレルギーの人は注意。'},

{id:'saw_palmetto', kind:'supp', name:'ノコギリヤシ', cat:'ハーブ',
 alias:['saw palmetto','ソウパルメット','セレノア'],
 tags:['hormone','antiplatelet_mild','psa_mask'],
 doseM:'320 mg/日（脂溶性抽出物）', doseF:'—（男性向け）', ul:'—',
 basis:'欧州の医薬品的使用・BPH領域のRCT', timing:'食後',
 note:'前立腺の検査値（PSA）を見かけ上下げることがあり、検診前は申告を。ホルモン系の薬との併用は要相談。'},

{id:'licorice', kind:'supp', name:'甘草（グリチルリチン）', cat:'ハーブ',
 alias:['カンゾウ','リコリス','グリチルリチン','licorice','glycyrrhizin','かんぞう','ぐりちるりちん'],
 tags:['k_lower','bp_up','high_risk','steroid_like'],
 doseM:'グリチルリチンとして40 mg/日未満に', doseF:'同左', ul:'グリチルリチン100 mg/日を超えない',
 basis:'EFSA/厚労省の注意喚起（偽アルドステロン症）',
 timing:'—', note:'★注意★ 長期・多量摂取で血圧上昇・むくみ・低カリウム（偽アルドステロン症）を起こす。漢方薬に広く含まれるため、漢方+のどあめ+ハーブティーの重複が起きやすい。'},

{id:'chasteberry', kind:'supp', name:'チェストベリー', cat:'ハーブ',
 alias:['チェストツリー','vitex','セイヨウニンジンボク'], tags:['hormone','dopamine','preg_avoid'],
 doseM:'20〜40 mg/日（乾燥果実抽出物）', doseF:'同左', ul:'—',
 basis:'ドイツで医薬品的使用・PMS領域のRCT', timing:'朝食後',
 note:'PMS領域で使われる。経口避妊薬・ホルモン療法・ドパミン作動薬との併用は要相談。妊娠中は避ける。'},

{id:'black_cohosh', kind:'supp', name:'ブラックコホシュ', cat:'ハーブ',
 alias:['black cohosh','ショウマ','ラケモサ'], tags:['hormone','liver_risk','preg_avoid'],
 doseM:'40〜80 mg/日（抽出物）', doseF:'同左', ul:'長期は6ヶ月程度で見直し',
 basis:'更年期領域のRCT・欧州の使用', timing:'食後',
 note:'まれに肝障害の症例報告があり、EU・豪州で注意表示。だるさ・黄色い尿・皮膚の黄変が出たら中止して受診。'},

{id:'isoflavone', kind:'supp', name:'大豆イソフラボン', cat:'ハーブ',
 alias:['イソフラボン','エクオール','soy isoflavone','ダイゼイン','ゲニステイン','だいずいそふらぼん','いそふらぼん'],
 tags:['hormone','thyroid','fe_absorb_down'],
 doseM:'—', doseF:'アグリコン換算で食事+サプリ合計70〜75 mg/日以内、サプリ上乗せは30 mg/日以内',
 ul:'食品安全委員会の安全な1日摂取目安上限 70〜75 mg/日（アグリコン換算）',
 basis:'内閣府食品安全委員会 2006年評価',
 timing:'食後', note:'豆腐・納豆・豆乳からの摂取分と合算して考える。乳がん治療中・ホルモン療法中は主治医に確認。'},

{id:'garlic', kind:'supp', name:'ニンニク（アリシン）', cat:'ハーブ',
 alias:['にんにく','ガーリック','アリシン','garlic','熟成黒にんにく'],
 tags:['antiplatelet','bp_lower','lipid_lower','cyp_mild','gi_irritant'],
 doseM:'600〜1,200 mg/日（抽出物）', doseF:'同左', ul:'—',
 basis:'複数RCT', timing:'食後',
 note:'血が固まりにくくなる方向に働く。抗凝固薬併用・手術前は要相談。抗HIV薬の血中濃度を下げる報告あり。'},

{id:'bilberry', kind:'supp', name:'ビルベリー（アントシアニン）', cat:'ハーブ',
 alias:['ビルベリー','アントシアニン','bilberry','ブルーベリー'],
 tags:['eye','antioxidant','antiplatelet_mild'],
 doseM:'アントシアニンとして40〜120 mg/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（目のピント調節）', timing:'食後',
 note:'高用量で血が固まりにくくなる方向の報告があり、抗凝固薬併用は控えめに。'},

{id:'cranberry', kind:'supp', name:'クランベリー', cat:'ハーブ',
 alias:['cranberry','キナ酸','プロアントシアニジン'], tags:['urine_acid','warfarin_interact','urinary'],
 doseM:'プロアントシアニジン36 mg/日相当', doseF:'同左', ul:'—',
 basis:'尿路領域のRCT', timing:'食後',
 note:'ワルファリンの効果を強める（出血傾向）報告があり、併用は避けるか医師管理下で。'},

{id:'garcinia', kind:'supp', name:'ガルシニア（HCA）', cat:'ハーブ',
 alias:['ガルシニアカンボジア','HCA','ヒドロキシクエン酸','garcinia'],
 tags:['fat_burn','liver_risk','serotonin','high_risk'],
 doseM:'HCAとして500〜1,500 mg/日', doseF:'同左', ul:'長期・高用量は避ける',
 basis:'減量領域のRCT（効果は小さい）', timing:'食前',
 note:'★注意★ 米国で肝障害の症例報告が複数あり（一部製品は回収）。減量効果は平均1kg未満との報告。抗うつ薬との併用は避ける。'},

{id:'yohimbe', kind:'supp', name:'ヨヒンベ（ヨヒンビン）', cat:'ハーブ',
 alias:['ヨヒンビン','yohimbe','yohimbine'], tags:['stimulant','bp_up','maoi_conflict','high_risk','arrhythmia'],
 doseM:'—（推奨しない）', doseF:'—（推奨しない）', ul:'—',
 basis:'—', timing:'—',
 note:'★高リスク★ 血圧上昇・不整脈・不安・まれに死亡例の報告があり、日本では医薬品成分に該当し食品への使用が認められていない。海外サプリの個人輸入で混入する例がある。使用しない。'},

{id:'capsaicin', kind:'supp', name:'カプサイシン（唐辛子）', cat:'ハーブ',
 alias:['唐辛子','カプサイシン','capsaicin','トウガラシ','とうがらし'], tags:['gi_irritant','thermogenic','bp_up'],
 doseM:'—（食品として少量）', doseF:'同左', ul:'—',
 basis:'—', timing:'食事と一緒に',
 note:'胃炎・胃潰瘍のある人は避ける。減量効果は限定的。'},

{id:'green_tea_ex', kind:'supp', name:'緑茶カテキン（EGCG濃縮）', cat:'ハーブ',
 alias:['カテキン','EGCG','緑茶抽出物','green tea extract','りょくちゃかてきん','かてきん'],
 tags:['liver_risk','fe_absorb_down','caffeine','fat_burn','high_risk'],
 doseM:'EGCGとして800 mg/日未満に', doseF:'同左', ul:'EFSAはサプリ由来EGCG 800 mg/日以上で肝障害リスクを指摘',
 basis:'EFSA 2018年評価',
 timing:'食後（空腹時の濃縮サプリは肝への負担が上がる）',
 note:'★注意★ 濃縮サプリを空腹時に高用量とると肝障害のリスク。飲み物としての緑茶は対象外。鉄の吸収も下げる。'},

/* ================= 抗酸化・機能性 ================= */
{id:'coq10', kind:'supp', name:'コエンザイムQ10', cat:'機能性',
 alias:['CoQ10','ユビキノール','ユビキノン','コエンザイム'],
 tags:['antioxidant','warfarin_antagonist','bp_lower','energy','fat_soluble'],
 doseM:'100〜200 mg/日', doseF:'同左', ul:'—',
 basis:'心血管・スタチン関連筋症状のRCT', timing:'食後（脂質と一緒で吸収↑）',
 note:'構造がビタミンKに似ており、ワルファリンの効果を弱める報告がある。スタチン服用中の筋痛対策で使われることがある。'},

{id:'alpha_lipoic', kind:'supp', name:'α-リポ酸', cat:'機能性',
 alias:['アルファリポ酸','チオクト酸','ALA','alpha-lipoic acid','りぽさん','あるふぁりぽさん'],
 tags:['antioxidant','glucose_lower','biotin_compete','thyroid','chelate'],
 doseM:'200〜600 mg/日', doseF:'同左', ul:'—',
 basis:'糖尿病性ニューロパチー領域のRCT', timing:'空腹時（食前30分）',
 note:'血糖を下げる方向に働くため糖尿病薬との併用で低血糖に注意。日本ではインスリン自己免疫症候群による低血糖の報告があり、体質によるリスクがある。'},

{id:'resveratrol', kind:'supp', name:'レスベラトロール', cat:'機能性',
 alias:['resveratrol','トランスレスベラトロール','赤ワインポリフェノール'],
 tags:['antioxidant','antiplatelet','cyp_mild','hormone'],
 doseM:'100〜500 mg/日', doseF:'同左', ul:'—', basis:'小規模RCT',
 timing:'食後', note:'血が固まりにくくなる方向・薬の代謝に影響する方向の報告がある。抗凝固薬併用は要相談。'},

{id:'astaxanthin', kind:'supp', name:'アスタキサンチン', cat:'機能性',
 alias:['astaxanthin','ヘマトコッカス'], tags:['antioxidant','eye','fat_soluble','bp_lower'],
 doseM:'6〜12 mg/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（目・肌）', timing:'食後',
 note:'脂溶性なので食後に。血圧を下げる方向の弱い報告があり、降圧薬併用時は測定を。'},

{id:'lutein', kind:'supp', name:'ルテイン・ゼアキサンチン', cat:'機能性',
 alias:['ルテイン','ゼアキサンチン','lutein','zeaxanthin'],
 tags:['eye','antioxidant','fat_soluble'],
 doseM:'ルテイン10 mg + ゼアキサンチン2 mg/日', doseF:'同左', ul:'—',
 basis:'AREDS2試験・機能性表示食品の届出実配合量', timing:'食後',
 note:'βカロテンと吸収経路を共有するため、同時に大量にとると互いの吸収が下がる。'},

{id:'nmn', kind:'supp', name:'NMN', cat:'機能性',
 alias:['ニコチンアミドモノヌクレオチド','nmn','NAD前駆体'], tags:['energy'],
 doseM:'250〜500 mg/日', doseF:'同左', ul:'—',
 basis:'小規模ヒト試験（長期の有効性・安全性データは限定的）', timing:'朝・空腹時',
 note:'ヒトでの長期データが乏しい新しい成分。抗がん剤治療中はNAD経路への影響が議論されており主治医に確認。'},

{id:'nattokinase', kind:'supp', name:'ナットウキナーゼ', cat:'機能性',
 alias:['納豆キナーゼ','nattokinase'], tags:['antiplatelet','fibrinolytic','high_risk'],
 doseM:'2,000 FU/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（血流）', timing:'夕食後',
 note:'血栓を溶かす方向に働く。抗凝固薬・抗血小板薬との併用や手術前は避ける。製品によりビタミンKを除去しているものがある。'},

{id:'glucosamine', kind:'supp', name:'グルコサミン', cat:'機能性',
 alias:['glucosamine','グルコサミン塩酸塩','N-アセチルグルコサミン'],
 tags:['joint','warfarin_interact','glucose_lower','allergen_shellfish'],
 doseM:'1,500 mg/日', doseF:'同左', ul:'—',
 basis:'変形性膝関節症領域のRCT（効果は製品・剤形で差）', timing:'食後',
 note:'ワルファリンの効果を強める（INR上昇）報告がある。甲殻類由来が多く、エビ・カニアレルギーの人は原料を確認。'},

{id:'chondroitin', kind:'supp', name:'コンドロイチン', cat:'機能性',
 alias:['chondroitin','コンドロイチン硫酸'], tags:['joint','warfarin_interact'],
 doseM:'800〜1,200 mg/日', doseF:'同左', ul:'—', basis:'変形性膝関節症領域のRCT',
 timing:'食後', note:'ヘパリン様の構造を持ち、抗凝固薬の効果を強める可能性が指摘されている。'},

{id:'hyaluronic', kind:'supp', name:'ヒアルロン酸', cat:'美容・その他',
 alias:['hyaluronic acid','ヒアルロン酸Na','ひあるろんさん'], tags:['skin_hair','joint'],
 doseM:'120 mg/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（肌の水分）', timing:'いつでも',
 note:'既知の重大な相互作用は報告されていない。'},

{id:'ceramide', kind:'supp', name:'セラミド（植物性）', cat:'美容・その他',
 alias:['グルコシルセラミド','こんにゃくセラミド','米セラミド','ceramide','せらみど'],
 tags:['skin_hair'], doseM:'0.6〜1.8 mg/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（肌の水分）', timing:'食後',
 note:'既知の重大な相互作用は報告されていない。'},

{id:'placenta', kind:'supp', name:'プラセンタ（豚・馬由来）', cat:'美容・その他',
 alias:['placenta','馬プラセンタ','豚プラセンタ','ぷらせんた'], tags:['skin_hair','hormone'],
 doseM:'—（製品差が大きい）', doseF:'—', ul:'—', basis:'—',
 timing:'就寝前', note:'経口サプリでの有効性のヒトデータは限定的。注射剤（ヒト由来）は献血制限の対象だが、経口の動物由来サプリは対象外。'},

{id:'probiotics', kind:'supp', name:'乳酸菌・ビフィズス菌（プロバイオティクス）', cat:'腸・その他',
 alias:['プロバイオティクス','乳酸菌','ビフィズス菌','probiotics','ラクトバチルス','にゅうさんきん','びふぃずすきん'],
 tags:['gut','immune'], doseM:'10億〜100億CFU/日', doseF:'同左', ul:'—',
 basis:'菌株別のRCT（効果は菌株ごとに異なる）', timing:'食後（胃酸が薄まるタイミング）',
 note:'抗菌薬と同時に飲むと菌が減るため2〜3時間ずらす。重度の免疫低下・中心静脈カテーテル使用中はまれに感染の報告があり避ける。'},

{id:'prebiotics', kind:'supp', name:'イヌリン・オリゴ糖（プレバイオティクス）', cat:'腸・その他',
 alias:['イヌリン','フラクトオリゴ糖','ガラクトオリゴ糖','難消化性デキストリン','食物繊維','しょくもつせんい','おりごとう','いぬりん'],
 tags:['gut','fiber','absorb_block','glucose_lower'],
 doseM:'5〜10 g/日', doseF:'同左', ul:'—',
 basis:'機能性表示食品の届出実配合量（お通じ・血糖・中性脂肪）',
 timing:'食前・食事と一緒', note:'いきなり多量にとるとお腹が張る・ガスが増える。少量から慣らす。薬やミネラルの吸収を遅らせることがある。'},

{id:'chitosan', kind:'supp', name:'キトサン', cat:'腸・その他',
 alias:['chitosan','キトサン','カニ由来'], tags:['absorb_block','fat_block','allergen_shellfish','warfarin_interact'],
 doseM:'1,000〜3,000 mg/日', doseF:'同左', ul:'—', basis:'脂質領域のRCT（効果は小さい）',
 timing:'食事の直前', note:'脂溶性ビタミン（A・D・E・K）の吸収を妨げる。ワルファリンの効果を強める報告あり。甲殻類アレルギーは避ける。'},

{id:'melatonin', kind:'supp', name:'メラトニン', cat:'機能性',
 alias:['melatonin','メラトニン'], tags:['sleep','sedative','hormone','jp_not_food'],
 doseM:'0.5〜3 mg（就寝前）', doseF:'同左', ul:'—',
 basis:'時差ぼけ・入眠困難領域のRCT',
 timing:'就寝30分〜1時間前',
 note:'★日本では食品への使用が認められておらず、国内でサプリとして販売できない（個人輸入のみ）。処方の類薬（ラメルテオンなど）は医師の管理下。抗凝固薬・免疫抑制薬・降圧薬との相互作用が報告されている。'},

{id:'caffeine', kind:'supp', name:'カフェイン（サプリ・錠剤）', cat:'機能性',
 alias:['caffeine','無水カフェイン','カフェイン錠','かふぇいん'],
 tags:['stimulant','ca_loss','fe_absorb_down','bp_up','arrhythmia','sleep_disturb'],
 doseM:'1回200 mg／1日400 mgまで', doseF:'1日400 mgまで（妊娠中は200 mgまで）', ul:'健康な成人400 mg/日（EFSA）',
 basis:'EFSA 2015年評価／内閣府食品安全委員会',
 timing:'午前〜午後早め（就寝6時間前以降は避ける）',
 note:'錠剤は一気に高用量になりやすく、日本でも急性中毒の事例がある。コーヒーやエナジードリンクとの合算で考える。'},

/* ================= 食品・飲料 ================= */
{id:'f_grapefruit', kind:'food', name:'グレープフルーツ（果実・ジュース）', cat:'食品',
 alias:['グレープフルーツジュース','GFJ','グレフル','ザボン','ブンタン','夏みかん','スウィーティー','ぐれーぷふるーつ'],
 tags:['cyp3a4_inhibitor'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'小腸の代謝酵素CYP3A4を数十時間ブロックする。「時間をずらす」では回避できないのが特徴。オレンジ・温州みかん・レモンは影響しない。'},

{id:'f_seville', kind:'food', name:'セビリアオレンジ・ポメロ・ライム', cat:'食品',
 alias:['ダイダイ','橙','ポメロ','文旦','ライム','ベルガモット'],
 tags:['cyp3a4_inhibitor'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'グレープフルーツと同じ酵素阻害成分（フラノクマリン）を含む柑橘。マーマレードにも注意。'},

{id:'f_natto', kind:'food', name:'納豆', cat:'食品',
 alias:['なっとう','納豆菌'], tags:['vit_k_rich','clotting','gut'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'ビタミンKが非常に多く、さらに腸内で作られる分も増えるため、ワルファリン服用中は原則禁止とされる。'},

{id:'f_greenleaf', kind:'food', name:'青汁・ケール・ほうれん草・ブロッコリー', cat:'食品',
 alias:['青汁','ケール','クロレラ','ほうれん草','ブロッコリー','小松菜','モロヘイヤ','大葉','あおじる','ほうれんそう','こまつな','けーる'],
 tags:['vit_k_rich','clotting','oxalate','fiber'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'ビタミンKが多い。ワルファリン服用中は「禁止」ではなく「量を急に増減させない」のが基本。シュウ酸もカルシウム・鉄の吸収を下げる。'},

{id:'f_milk', kind:'food', name:'牛乳・ヨーグルト・チーズ', cat:'食品',
 alias:['乳製品','牛乳','ヨーグルト','チーズ','ミルク','ぎゅうにゅう','にゅうせいひん','よーぐると','ちーず'],
 tags:['ca_rich','chelate','divalent_cation'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'カルシウムが金属イオンと結合し、鉄・亜鉛や一部の抗菌薬（テトラサイクリン系・ニューキノロン系）の吸収を大きく下げる。2時間以上ずらす。'},

{id:'f_coffee', kind:'food', name:'コーヒー', cat:'食品',
 alias:['珈琲','エスプレッソ','カフェラテ'], tags:['caffeine','tannin','fe_absorb_down','ca_loss','stimulant'],
 doseM:'—（1杯あたりカフェイン約60〜100 mg）', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'タンニンが鉄の吸収を下げる。カフェインサプリやエナジードリンクとの合算に注意。'},

{id:'f_tea', kind:'food', name:'緑茶・紅茶・ウーロン茶', cat:'食品',
 alias:['お茶','緑茶','紅茶','烏龍茶','ほうじ茶','麦茶以外のお茶','おちゃ','りょくちゃ','こうちゃ','うーろんちゃ'],
 tags:['caffeine','tannin','fe_absorb_down','stimulant'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'鉄剤とは30分〜1時間ずらすのが無難。飲み物としての量なら濃縮カテキンサプリのような肝リスクはない。'},

{id:'f_alcohol', kind:'food', name:'アルコール（お酒）', cat:'食品',
 alias:['酒','ビール','ワイン','日本酒','焼酎','ウイスキー','アルコール','おさけ','さけ','あるこーる','びーる'],
 tags:['sedative','alcohol','liver_risk','b1_loss','gi_irritant','dehydrate'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'肝臓に負担をかける成分（緑茶濃縮・ガルシニア・ブラックコホシュ等）や眠くなる成分と重なると影響が増幅する。'},

{id:'f_energy', kind:'food', name:'エナジードリンク', cat:'食品',
 alias:['エナドリ','レッドブル','モンスター','ZONE'],
 tags:['caffeine','stimulant','bp_up','sugar','arrhythmia'],
 doseM:'—（1本あたりカフェイン約80〜150 mg）', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'カフェイン錠・プレワークアウトとの併用で1日400 mgをすぐ超える。'},

{id:'f_wholegrain', kind:'food', name:'玄米・全粒穀物・豆類（フィチン酸）', cat:'食品',
 alias:['玄米','全粒粉','ふすま','大豆','豆','ナッツ','フィチン酸'],
 tags:['phytate','chelate','fiber'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'フィチン酸が亜鉛・鉄・カルシウムと結合して吸収を下げる。ミネラルサプリは食事から1〜2時間ずらすと影響を減らせる。'},

{id:'f_rawegg', kind:'food', name:'生卵の白身', cat:'食品',
 alias:['生卵','卵白','アビジン','なまたまご','らんぱく'], tags:['biotin_block'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'白身のアビジンがビオチンと結合して吸収を妨げる。加熱すればこの作用はなくなる。'},

{id:'f_tyramine', kind:'food', name:'熟成チーズ・赤ワイン・干物（チラミン）', cat:'食品',
 alias:['チラミン','熟成チーズ','赤ワイン','サラミ','干物','ぬか漬け','ちらみん','あかわいん','ひもの','じゅくせいちーず'],
 tags:['tyramine','bp_up'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'MAO阻害薬やチラミン分解を妨げる成分と重なると、血圧が急上昇する（チーズ効果）。'},

{id:'f_highsalt', kind:'food', name:'高塩分の食事', cat:'食品',
 alias:['塩分','ナトリウム','しょっぱいもの'], tags:['bp_up','ca_loss'],
 doseM:'食塩相当量 男7.5g / 女6.5g 未満（目標量）', doseF:'—', ul:'—',
 basis:'日本人の食事摂取基準2020（目標量）', timing:'—',
 note:'カルシウムの尿への排出を増やす。骨対策と塩分対策はセットで考える。'},

{id:'f_soy', kind:'food', name:'大豆製品（豆腐・豆乳・味噌）', cat:'食品',
 alias:['豆腐','豆乳','味噌','きなこ','枝豆','大豆'],
 tags:['isoflavone_rich','thyroid','fe_absorb_down','phytate'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'甲状腺ホルモン薬（レボチロキシン）の吸収を下げるため4時間ほどずらす。イソフラボンサプリとの合算にも注意。'},

{id:'f_licorice_food', kind:'food', name:'甘草入りのど飴・漢方薬・リコリス菓子', cat:'食品',
 alias:['のど飴','漢方','葛根湯','芍薬甘草湯','リコリス菓子','のどあめ','かんぽう','かっこんとう','しゃくやくかんぞうとう'],
 tags:['k_lower','bp_up','steroid_like'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'甘草は漢方処方の7割前後に含まれる。複数の漢方+のど飴+ハーブティーで気づかず過剰になりやすい。'},

{id:'f_cranberry_juice', kind:'food', name:'クランベリージュース', cat:'食品',
 alias:['クランベリージュース'], tags:['warfarin_interact','urine_acid'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'ワルファリン服用中は大量摂取を避ける（出血傾向を強める報告）。'},

{id:'f_water', kind:'food', name:'水・麦茶', cat:'食品',
 alias:['水','白湯','麦茶','ミネラルウォーター','みず','むぎちゃ','さゆ'], tags:[], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'サプリを飲むときの基本。硬水のミネラルウォーターはカルシウム・マグネシウムを含むが、通常量では影響しない。'},

/* ================= 薬の系統（参考・注意喚起用） ================= */
{id:'d_warfarin', kind:'drug', name:'ワルファリン（抗凝固薬）', cat:'薬（参考）',
 alias:['ワーファリン','warfarin','抗凝固薬','わるふぁりん','わーふぁりん','こうぎょうこやく'], tags:['anticoagulant','narrow_ti','rx'],
 doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'効き目の幅が狭く、食品・サプリの影響を最も受けやすい薬。このアプリで△・×が出た組み合わせは必ず主治医・薬剤師に確認。'},

{id:'d_doac', kind:'drug', name:'DOAC・抗血小板薬', cat:'薬（参考）',
 alias:['エリキュース','リクシアナ','イグザレルト','バイアスピリン','アスピリン','クロピドグレル','プラビックス','こうけっしょうばんやく','あすぴりん'],
 tags:['anticoagulant','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'血を固まりにくくする薬。抗血小板作用のあるサプリと重なると出血リスクが上がる。'},

{id:'d_ssri', kind:'drug', name:'抗うつ薬（SSRI/SNRI/MAO阻害薬）', cat:'薬（参考）',
 alias:['SSRI','SNRI','MAO阻害薬','パキシル','ジェイゾロフト','レクサプロ','サインバルタ','セレギリン','こううつやく'],
 tags:['serotonin_rx','maoi','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'セロトニンに働くサプリと重なるとセロトニン症候群（発汗・震え・混乱）のリスク。'},

{id:'d_statin', kind:'drug', name:'スタチン（コレステロール薬）', cat:'薬（参考）',
 alias:['スタチン','リピトール','クレストール','メバロチン','アトルバスタチン','シンバスタチン','すたちん','これすてろーるのくすり'],
 tags:['cyp3a4_substrate','rx','muscle_risk'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'一部のスタチンはグレープフルーツで血中濃度が上がり、筋障害のリスクが増す。'},

{id:'d_bp', kind:'drug', name:'降圧薬', cat:'薬（参考）',
 alias:['降圧剤','血圧の薬','アムロジピン','ARB','ACE阻害薬','カルシウム拮抗薬','利尿薬','こうあつやく','けつあつのくすり','こうあつざい'],
 tags:['bp_rx','cyp3a4_substrate','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'カルシウム拮抗薬はグレープフルーツで効きが強まる。血圧を下げるサプリとの重複でふらつきが出ることがある。'},

{id:'d_diabetes', kind:'drug', name:'糖尿病治療薬', cat:'薬（参考）',
 alias:['インスリン','メトホルミン','SU剤','DPP-4','SGLT2','糖尿病の薬','とうにょうびょう','とうにょうびょうのくすり','いんすりん'],
 tags:['glucose_rx','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'血糖を下げるサプリと重なると低血糖のリスク。自己測定と主治医への相談を。'},

{id:'d_thyroid', kind:'drug', name:'甲状腺ホルモン薬', cat:'薬（参考）',
 alias:['チラーヂン','レボチロキシン','メルカゾール','甲状腺の薬','こうじょうせん','こうじょうせんのくすり'],
 tags:['thyroid_rx','chelate_victim','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'鉄・カルシウム・大豆・食物繊維で吸収が大きく落ちる。起床時に空腹で飲み、サプリは4時間空ける。'},

{id:'d_op', kind:'drug', name:'経口避妊薬・ホルモン療法', cat:'薬（参考）',
 alias:['ピル','低用量ピル','OC','経口避妊薬','HRT','ホルモン補充療法','ぴる','けいこうひにんやく','ていようりょうぴる'],
 tags:['cyp3a4_substrate','hormone_rx','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'セントジョーンズワートで効果が落ち、避妊失敗の報告がある。'},

{id:'d_abx', kind:'drug', name:'抗菌薬（テトラサイクリン系・ニューキノロン系）', cat:'薬（参考）',
 alias:['抗生物質','ミノマイシン','クラビット','レボフロキサシン','テトラサイクリン','セフェム','こうきんやく','こうせいぶっしつ'],
 tags:['chelate_victim','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'鉄・カルシウム・マグネシウム・亜鉛と結合して吸収が落ちる。2時間以上ずらす。'},

{id:'d_sedative', kind:'drug', name:'睡眠薬・抗不安薬', cat:'薬（参考）',
 alias:['睡眠薬','抗不安薬','ベンゾジアゼピン','マイスリー','デパス','ルネスタ','ベルソムラ','すいみんやく','こうふあんやく'],
 tags:['sedative_rx','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'眠くなるサプリ・アルコールと重なると、ふらつき・記憶の抜け・転倒のリスクが上がる。'},

{id:'d_immunosuppress', kind:'drug', name:'免疫抑制薬・抗がん剤', cat:'薬（参考）',
 alias:['免疫抑制剤','タクロリムス','シクロスポリン','プログラフ','抗がん剤','分子標的薬','めんえきよくせいやく','こうがんざい'],
 tags:['cyp3a4_substrate','narrow_ti','immunosuppress','rx'], doseM:'—', doseF:'—', ul:'—', basis:'—', timing:'—',
 note:'血中濃度の管理が命に関わる薬。サプリの自己判断併用は行わず、必ず主治医に全て申告する。'},
];
